# SQLALCHEMY_DATABASE_URI = 'mysql:/:xiaobing@127.0.0.1:3306/cleanblog'
# SQLALCHEMY_TRACK_MODIFICATIONS = True
# DEBUG = True
# SECRET_KEY = '1werw3@#$@#%$^%&^%&^*&(*(()3he6'
# BABEL_DEFAULT_LOCALE = 'zh_Hans_CN'
#
# UPLOAD_FOLDER = 'F:\\uploadFile'
# MAX_CONTENT_LENGTH = 16 * 1024 * 1024


HOST = '114.55.252.134'
PORT = '3306'
DATABASE = 'blog'
USERNAME = 'root'
PASSWORD = 'Blog@2022'

DB_URI = f"mysql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}?charset=utf8"
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True
